### ISSUE TITLE
Добавить создание сущности "Персона" при добавлении пользователя

### ISSUE THREAD

**Issue by gooamoko** [java-beginers/equipment#10]
Предлагаю при добавлении новой сущности "User" проверять по адресу электронной почты наличие или отсутствие соответствующей персоны. Если такая персона есть, то не создавать новую. Если же персона с таким адресом электронной почты отсутствует, то необходимо добавить персону.

Для реализации такой доработки желательно вместо отдельных полей "Фамилия" "Имя" "Отчество" сделать одно поле "Полное имя". В таком случае, можно просто скопировать данные из сущности User в сущность Person

**Comment by MrRumm** [comment]
После обсуждения было решено, что эта задача нецелесообразна так что пока закрыта
