### ISSUE TITLE
Доработать сущность User для обеспечения возможности отключения и блокировки.

### ISSUE THREAD

**Issue by gooamoko** [java-beginers/equipment#2]
Добавить в класс сущности пользователя User и (соответственно) в таблицу БД следующие поля

- disabled (boolean)
- expired (boolean) Опционально.

Если будет добавляться поле expired, то также необходима логика по управлению скором годности учетной записи. Например, политика смены пароля раз в месяц. Для этого можно добавить поле pwdchange_date с типом date (дата).

**Comment by MrRumm** [comment]
В классе сущности и в таблице БД сущности enabled (boolean) для проверки работоспособности учетной записи, и поле pwdchange_date. Поле expired не вижу смысла добавлять.
