### ISSUE TITLE
Доработать механизм создания "Виртуального администратора"

### ISSUE THREAD

**Issue by gooamoko** [java-beginers/equipment#3]
После выполнения задачи #2 необходимо доработать механизм создания виртуального администратора. Нужны следующие доработки:

- Обеспечить чтобы виртуальный администратор был всегда активен и его пароль никогда не был просрочен.
- Обеспечить создание виртуального администратора ТОЛЬКО тогда, когда в файле application.properties указаны параметры admin.login и admin.password

**Comment by MrRumm** [comment]
В файле CurrentUserDetailsService добавлено значение user.setPwdchangedate(new Date()); для администратора, вследствие чего пароль не будет просрочен. По поводу второго пункта вы говорили что он уже работает так что не знаю стоит ли закрывать задачу!
