### ISSUE TITLE
Реализовать возможность добавления (регистрации) пользователей

### ISSUE THREAD

**Issue by gooamoko** [java-beginers/equipment#4]
После выполнения задачи #3, требуется реализовать возможность для добавления новых пользователей. Здесь и далее под пользователями подразумеваются те, кто может логиниться в приложение и работать в нем.

Предлагаю следующий подход. Администратор имеет возможность добавлять нового пользователя. Статус пользователя (обычный, либо администратор) указывается при добавлении. Также указываются другие параметры. 

Надо как-то продумать механизм указания пароля. Предлагаю добавить поле "needpwdchange" логического типа, которое будет указывать на необходимость смены пароля пользователем при входе.

В этом случае администратор задает пароль, сообщает его пользователю любым известным им способом и устанавливает флаг обязательной смены пароля. Пользователь осуществляет вход и меняет пароль.
Необходимо проверить возможность реализации такого сценария стандартными средствами Spring Security, то есть посмотреть:

- как поведет себя Spring Security при попытки авторизоваться просроченным пользователем.
- можно ли настроить в конфигурации форму для смены пароля, если он просрочен.

Возможно, это поможет:

- [Ссылка 1](http://www.baeldung.com/spring-security-registration-i-forgot-my-password)
- [Ссылка 2](https://stackoverflow.com/questions/10839629/spring-security-password-change-page-implementation)
- [Ссылка 3](https://stackoverflow.com/questions/8470173/forcing-user-to-change-expired-password-in-spring-security)

**Comment by MrRumm** [comment]
Задача реализована, создана страница для отображения и добавления новых пользователей. Механизм смены пароля так же предусмотрен.
