### ISSUE TITLE
Реализовать страницу управления пользователями

### ISSUE THREAD

**Issue by gooamoko** [java-beginers/equipment#5]
После выполнения задачи #4, необходимо создать какую-то страницу, где можно было бы видеть список пользователей и иметь возможность их редактирования, удаления, смены пароля и блокировки.

При смене пароля желательно предусмотреть автоматическое выставление флага "менять пароль при следующем входе в систему", который упоминался в задаче #4.

В плане удаления пользователей надо продумать следующий момент: что делать с оборудованием и другими связанными сущностями. Например, удаляется сотрудник, на подотчете которого есть какое-то оборудование. Предлагаю запретить возможность удаления тех пользователей, на которых что-то числится.

Блокировка пользователей должна выполняться не зависимо от количества оборудования, которое на них числится.

**Comment by MrRumm** [comment]
Задача реализована, создана страница для отображения и добавления новых пользователей. Механизм смены пароля так же предусмотрен.
